development:
  adapter: postgresql
  database: bandmatch_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: bandmatch_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: bandmatch_production
  pool: 5
  timeout: 5000